version: "3"
services:
  spark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-notebook
    ports:
      - "9100:8888"
    entrypoint: bash
    command: -c "jupyter lab --ip=0.0.0.0 --port=8888 --allow-root"